import regex
import logging
from typing import List

from ..interfaces.url_filter_strategy import URLFilterStrategy
from ...services.llm.llm_manager import LLMManager
from ...config.prompts import FILTERING_REGEX_CHAT_PROMPT

logger = logging.getLogger(__name__)


class RegexURLFilter(URLFilterStrategy):
    """
    Filter URLs using regex patterns generated by LLM
    """

    def __init__(self, model: str):
        self.model = model

    async def filter_urls(
        self,
        urls: List[str],
    ) -> List[str]:
        filtered_urls = []

        # Generate regex pattern
        regex_pattern = await self.generate_regex_pattern(
            urls[:500]
        )  # test with 250 samples

        # Filter URLs using the pattern
        for url in urls:
            if regex.search(regex_pattern, url):
                filtered_urls.append(url)
            else:
                logger.warning(f"Doesn't match: {url}")

            logger.info(
                f"Filtered {len(filtered_urls)} URLs from {len(urls)} total using regex"
            )
        return filtered_urls

    async def generate_regex_pattern(
        self,
        sample_urls: List[str],
    ) -> str:
        # Get regex pattern from LLM

        llm_manager = LLMManager(
            [self.model], sample_urls, FILTERING_REGEX_CHAT_PROMPT, None
        )
        response = llm_manager.call_llm()

        return self.format_response(response.get("response").content)

    def format_response(self, response: str) -> str:
        """Format the regex pattern response from LLM"""
        return self.clean_response(response)
